package com.example.trenucizapamcenje


object Constants {
    const val SERVER_IP_ADRESS ="http://10.234.212.58:4000/"
    const val emptyFieldsError ="Greška: Sva polja su obavezna!"
    const val wrongCredentialsError = "Greška: Uneti kredencijali nisu ispravni!"
    const val eventsTitle = "ORGANIZOVANI DOGAĐAJI"
    const val seeMore = "Pogledaj vise događaja"
    const val phoneNumber = "Telefon: +381 64 123 45 67"
    const val emailAddress = "Email adresa: trenutcizapamcenje@gmail.com"
    const val workingTime = "Radno vreme :  Ponedeljak–Petak, 8–20 h"
    const val appName = "Trenuci za pamćenje"
    const val nameCut = "Trenuci\n za pamćenje"
    const val offersTitle = "Aktuelne ponude"
    const val prefName = "Moments_to_remember"
    const val prefCurrentOffer = "Current offer"
    const val appointmentConditions = "Uslovi pri zakazivanju:"
    const val minGuests ="Minimalan broj gostiju:"
    const val maxGuests = "Maksimalan broj gostiju:"
    const val priceByGuest ="Cena po gostu:"
    const val appoint = "Zakaži svoj termin"
    const val myProfile = "Moj profil"
    const val name = "Ime:"
    const val surname ="Prezime:"
    const val address = "Adresa:"
    const val contactPhone = "Kontakt telefon:"
    const val logout = "Odjavi se"
    const val changeData = "Izmena podataka"
    const val changePassword = "Izmena lozinke"
    const val prefCurrentUser = "Current user"
    const val undo = "Otkaži"
    const val save = "Sačuvaj"
    const val welcome = "Dobro došli"
    const val titleChangePassword = "Promena lozinke"
    const val inputPassword = "Nova lozinka:"
    const val inputPasswordAgain = "Ponovo unesi:"
    const val errorchangingPassword = "Greška: Lozinke se ne poklapaju"
}