import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const inter = localFont({
  src: 'fonts/inter.ttf',
  variable: '--font-inter'
})
const italianno = localFont({
  src: 'fonts/italianno.ttf',
  variable: '--font-italianno'
})
const lato = localFont({
  src: 'fonts/lato.ttf',
  variable: '--font-lato'
})
const lunasima = localFont({
  src: 'fonts/lunasima.ttf',
  variable: '--font-lunasima'
})
const montserrat = localFont({
  src: 'fonts/montserrat.ttf',
  variable: '--font-montserrat'
})
const cormorantGaramond = localFont({
  src: 'fonts/cormorant_garamond.ttf',
  variable: '--font-cormorant-garamond'
})
const nunito = localFont({
  src: 'fonts/nunito.ttf',
  variable: '--font-nunito'
})
const roboto = localFont({
  src: 'fonts/roboto.ttf',
  variable: '--font-roboto'
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${italianno.variable} ${lato.variable} ${lunasima.variable} ${montserrat.variable} ${cormorantGaramond.variable} ${nunito.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
